version: '3.6'
services:
  db:
    container_name: jpashop_db
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: jpashop
      TZ: "Asia/Seoul"
    volumes:
      - ./postgres/initdb:/docker-entrypoint-initdb.d
    tty: true
    ports:
      - "5434:5432"
